### ISSUE TITLE
Change color of channel title

### ISSUE THREAD

**Issue by coyotte508** [po-devs/webclient#136]
The color of the channel title is fine when the channel is selected (and it should stay that way), but when it's not it's grey on grey and it's not great. 

When the channel is not selected, change the color to a blacker one. 

To change the color, here's an example:

``` css
.tab-active .channel-title {
    color:#2658b7 !important;
}
```

of course it's not tab-active, and the rule should be before this one so this one (the one that is blue when there's new activity) has priority.
